Repository wecode-bootcamp-korea/25-1st-NULLFICTION-frontend, pull requests merged in 2021-10, with the labels that each got.

#3 [25기 정찬영] Add: 상품 상세 페이지 작업
  public/images/images.js
  public/images/productDetail/arrow.png
  public/images/productDetail/myImage.jpg
  public/images/productDetail/myImage2.jpg
  public/images/productDetail/myImage3.jpg
  public/index.html
  src/Routes.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/components/ProductImage/ProductImage.js
  src/pages/ProductDetail/components/ProductImage/ProductImage.scss
  src/pages/ProductDetail/components/ProductInfo/ProductCategory/ProductCategory.js
  src/pages/ProductDetail/components/ProductInfo/ProductCategory/ProductCategory.scss
  src/pages/ProductDetail/components/ProductInfo/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/components/ProductInfo/ProductDescription/ProductDescription.scss
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.js
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.scss
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductOption/ProductOption.js
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductOption/ProductOption.scss
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductSelect.js
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductSelect.scss
Labels: Status: Accepted

#22 Add: 상품 리스트 모달창 기능 구현
  src/pages/Product/EachProduct.js
  src/pages/Product/EachProduct.scss
  src/pages/Product/Modal.js
  src/pages/Product/Modal.scss
  src/pages/Product/Product.js
Labels: Status: 리뷰 요청

#23 [25기 정찬영] 상세 페이지 오류 수정
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/components/ProductImage/ProductImage.js
  src/pages/ProductDetail/components/ProductImage/index.js
  src/pages/ProductDetail/components/ProductInfo/ProductCategory/index.js
  src/pages/ProductDetail/components/ProductInfo/ProductDescription/ProductDescription.js
  src/pages/ProductDetail/components/ProductInfo/ProductDescription/index.js
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.js
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductOption/index.js
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductSelect.js
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/index.js
  src/pages/ProductDetail/components/ProductInfo/index.js
Labels: Status: 리뷰 요청, Status: Rebase 요청

#26 [25기 정찬영] 백엔드 통신을 위한 URL 및 토큰 변경
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/components/ProductInfo/ProductSelect/ProductSelect.js
Labels: Status: 리뷰 요청

#28 [25기 정찬영] import 중복 수정
  src/Routes.js
Labels: Status: 리뷰 요청

#29 [25기 이선호] 회원가입 유효성검사 로직 추가
  src/pages/Join/Join.js
  src/pages/Join/config.js
  src/pages/Login/Login.js
  src/pages/Login/config.js
Labels: Status: 리뷰 요청
